import destr from "destr";
import fs from "fs-extra";
import path from "pathe";

// ▶️ pnpm tsx addons/scripts/mdxBuilder.ts
// ▶️ pnpm tsx addons/scripts/mdxBuilder.ts --generate-structure

/* eslint-disable @typescript-eslint/no-unsafe-argument */
/* eslint-disable @typescript-eslint/no-explicit-any */
/* eslint-disable @typescript-eslint/no-unsafe-assignment */
/* eslint-disable @typescript-eslint/no-unsafe-member-access */

const messagesDirectory = "messages";
const outputDirectory = "src/content/docs";

interface JsonContent {
  content?: string;
  title?: string;
}

interface SitemapEntry {
  dateCreated: string;
  dateUpdated: string;
  ext: string;
}

async function generateFileFromJson(
  filePath: string,
  outputPath: string,
  extension: string,
) {
  const fileContent = await fs.readFile(filePath, "utf8");
  const jsonContent = destr<JsonContent>(fileContent);

  const fileName = path.basename(filePath, ".json");
  const fileExtension = extension === "mdx" ? ".mdx" : ".md";
  const outputFilePath = outputPath.replace(/\.md$/, fileExtension);

  const mdContent = `<!--
    This is a generated file. Do not edit this file directly.
    To make changes, edit the original i18n file located at: ${filePath}.
    Date Created: ${new Date().toLocaleDateString()}
    Last Updated: ${new Date().toLocaleDateString()}
-->

# ${jsonContent?.title ?? fileName}

${jsonContent?.content ?? ""}
`;

  await fs.mkdir(path.dirname(outputFilePath), { recursive: true });
  await fs.writeFile(outputFilePath, mdContent, "utf8");
  console.log(`Generated ${outputFilePath}`);
}

async function processDirectory(
  inputDirectory: string,
  outputDirectory_: string,
  localeKey = "root",
) {
  const files = await fs.readdir(inputDirectory);

  for (const file of files) {
    const fullPath = path.join(inputDirectory, file);
    const stats = await fs.stat(fullPath);

    if (stats.isDirectory()) {
      await processDirectory(fullPath, outputDirectory_, localeKey);
    } else if (stats.isFile() && path.extname(file) === ".json") {
      // Skip processing sitemap.json
      if (file === "sitemap.json") {
        continue;
      }

      const relativePath = path.relative(messagesDirectory, fullPath);
      const outputFilePath = path
        .join(
          outputDirectory_,
          localeKey === "root" ? "" : localeKey,
          relativePath,
        )
        .replace(/\.json$/, ".md");

      const fileContent = await fs.readFile(fullPath, "utf8");
      const jsonContent = destr<SitemapEntry>(fileContent);

      await generateFileFromJson(fullPath, outputFilePath, jsonContent.ext);
    }
  }
}

async function generateStructureFromConfig() {
  const configPath = path.resolve("astro.config.mjs");
  const sitemapPath = path.resolve(messagesDirectory, "sitemap.json");

  console.log(
    "Updating content folder structure based on astro.config.mjs and sitemap.json...",
  );

  if (
    !(await fs.pathExists(configPath)) ||
    !(await fs.pathExists(sitemapPath))
  ) {
    console.warn(`Reading ${configPath} and ${sitemapPath}`);
    console.error("astro.config.mjs or sitemap.json not found.");
    process.exit(1);
  }

  const { default: config } = await import(configPath);
  const sitemapContent = await fs.readFile(sitemapPath, "utf8");
  // biome-ignore lint/suspicious/noExplicitAny: <explanation>
  const sitemap = destr<Record<string, any>>(sitemapContent);

  for (const localeKey of Object.keys(config.locales)) {
    await createFolderStructure(sitemap, localeKey);
  }
}

async function createFolderStructure(
  // biome-ignore lint/suspicious/noExplicitAny: <explanation>
  sitemap: Record<string, any>,
  localeKey: string,
  currentPath = "",
) {
  for (const key of Object.keys(sitemap)) {
    const value = sitemap[key];

    if (typeof value.ext === "string") {
      const folderPath = path.join(
        messagesDirectory,
        localeKey === "root" ? "" : localeKey,
        currentPath,
      );

      await fs.mkdir(folderPath, { recursive: true });
      const jsonFilePath = path.join(folderPath, `${key}.json`);

      if (!(await fs.pathExists(jsonFilePath))) {
        await fs.writeFile(
          jsonFilePath,
          JSON.stringify({ title: "", content: "" }, null, 2),
          "utf8",
        );
        console.log(`Created ${jsonFilePath}`);
      }
    } else {
      await createFolderStructure(
        value,
        localeKey,
        path.join(currentPath, key),
      );
    }
  }
}

async function main() {
  const args = process.argv.slice(2);

  if (args.includes("--generate-structure")) {
    await generateStructureFromConfig();
  } else {
    await processDirectory(messagesDirectory, outputDirectory);
  }
}

main().catch((error: unknown) => {
  console.error(error);
});
